gestionBusScolaire/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
        
from django.urls import path,include
from rest_framework import routers
router = routers.DefaultRouter()

from transport_scolaire.view_sets import (
     AnneeInscriptionViewSet,
     ChauffeurViewSet,
     EcoleAssignationViewSet,
     TypeVehiculeViewSet,
     BusViewSet,
     LieuLigneViewSet,
     LigneViewSet,
     LieuRamassageViewSet,
     OrdreLieuViewSet,
     EcoleViewSet,
     ClasseViewSet,
     ParentViewSet,
     EleveViewSet,
     InscriptionViewSet,
     ItineraireViewSet,
     HoraireViewSet,
     BusAssignationViewSet,
     AssignationItineraireViewSet,
)

router.register('transport_scolaire/chauffeurs', ChauffeurViewSet,basename='transport_scolaire.chauffeurs')
router.register('transport_scolaire/typevehicules', TypeVehiculeViewSet,basename='transport_scolaire.typevehicules')
router.register('transport_scolaire/buss', BusViewSet,basename='transport_scolaire.buss')
router.register('transport_scolaire/lieulignes', LieuLigneViewSet,basename='transport_scolaire.lieulignes')
router.register('transport_scolaire/lignes', LigneViewSet,basename='transport_scolaire.lignes')
router.register('transport_scolaire/lieuramassages', LieuRamassageViewSet,basename='transport_scolaire.lieuramassages')
router.register('transport_scolaire/ordrelieus', OrdreLieuViewSet,basename='transport_scolaire.ordrelieus')
router.register('transport_scolaire/ecoles', EcoleViewSet,basename='transport_scolaire.ecoles')
router.register('transport_scolaire/classes', ClasseViewSet,basename='transport_scolaire.classes')
router.register('transport_scolaire/parents', ParentViewSet,basename='transport_scolaire.parents')
router.register('transport_scolaire/annee_inscriptions', AnneeInscriptionViewSet,basename='transport_scolaire.annee_inscriptions')
router.register('transport_scolaire/eleves', EleveViewSet,basename='transport_scolaire.eleves')
router.register('transport_scolaire/inscriptions', InscriptionViewSet,basename='transport_scolaire.inscriptions')
router.register('transport_scolaire/itineraires', ItineraireViewSet,basename='transport_scolaire.itineraires')
router.register('transport_scolaire/horaires', HoraireViewSet,basename='transport_scolaire.horaires')
router.register('transport_scolaire/busassignations', BusAssignationViewSet,basename='transport_scolaire.busassignations')
router.register('transport_scolaire/ecoleassignations', EcoleAssignationViewSet,basename='transport_scolaire.ecoleassignations')
router.register('transport_scolaire/assignationitineraires', AssignationItineraireViewSet,basename='transport_scolaire.assignationitineraires')

from app_master.views import HomeViewPage

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from authentication.views_set import TokenCheckView
from django.views.generic.base import RedirectView
from django.contrib.auth import get_user_model

from transport_scolaire.view_sets import CountViewSet,AssignationBusItineraireViewSet

User=get_user_model()
class CustomTokenObtainPairView(TokenObtainPairView):
    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)

        # Effectuez des modifications sur la réponse si nécessaire
        user = User.objects.get(username=request.data.get('username'))
        role = user.role if not user.is_superuser else "admin"

        # Ajoutez les informations de l'utilisateur à la réponse
        response.data['user'] = {
            'id': user.id,
            'username': user.username,
            'email': user.email,
            'role': role
        }

        return response

urlpatterns = [
     path('admin/', admin.site.urls),
     path('api/', include(router.urls)),     path('',HomeViewPage.as_view(),name='dashboard'),
     path('transport_scolaire/', include('transport_scolaire.urls')),
     path('api/ts/assignation_itineraire_bus', AssignationBusItineraireViewSet.as_view(),name='transport_scolaire:assignation_itineraire_bus'),

     path('api-auth/', include('rest_framework.urls')),
     path('api/token/', CustomTokenObtainPairView.as_view(), name='obtain_tokens'),
     path('api/token/check/', TokenCheckView.as_view(), name='check_tokens'),
     path('api/token/refresh/', TokenRefreshView.as_view(), name='refresh_token'),
     path('api/counts/', CountViewSet.as_view(), name='count'),
    #   path('<path:dummy>', HomeViewPage.as_view()),  # Redirige tous les autres URL vers HomeViewPage.as_view()
    #  path('<path:dummy>', RedirectView.as_view(url='/')),  # Redirige tous les autres URL vers '/'
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns +=[path('<path:dummy>', RedirectView.as_view(url='/')),]

transport_scolaire/urls.py
from django.urls import path

from .views_generic import (
      ChauffeurListView, ChauffeurDetailView, ChauffeurCreateView, ChauffeurUpdateView, ChauffeurDeleteView,
      TypeVehiculeListView, TypeVehiculeDetailView, TypeVehiculeCreateView, TypeVehiculeUpdateView, TypeVehiculeDeleteView,
      BusListView, BusDetailView, BusCreateView, BusUpdateView, BusDeleteView,
      LieuLigneListView, LieuLigneDetailView, LieuLigneCreateView, LieuLigneUpdateView, LieuLigneDeleteView,
      LigneListView, LigneDetailView, LigneCreateView, LigneUpdateView, LigneDeleteView,
      LieuRamassageListView, LieuRamassageDetailView, LieuRamassageCreateView, LieuRamassageUpdateView, LieuRamassageDeleteView,
      OrdreLieuListView, OrdreLieuDetailView, OrdreLieuCreateView, OrdreLieuUpdateView, OrdreLieuDeleteView,
      EcoleListView, EcoleDetailView, EcoleCreateView, EcoleUpdateView, EcoleDeleteView,
      ClasseListView, ClasseDetailView, ClasseCreateView, ClasseUpdateView, ClasseDeleteView,
      ParentListView, ParentDetailView, ParentCreateView, ParentUpdateView, ParentDeleteView,
      EleveListView, EleveDetailView, EleveCreateView, EleveUpdateView, EleveDeleteView,
 
      ItineraireListView, ItineraireDetailView, ItineraireCreateView, ItineraireUpdateView, ItineraireDeleteView,
      HoraireListView, HoraireDetailView, HoraireCreateView, HoraireUpdateView, HoraireDeleteView,
      BusAssignationListView, BusAssignationDetailView, BusAssignationCreateView, BusAssignationUpdateView, BusAssignationDeleteView,
      AssignationItineraireListView, AssignationItineraireDetailView, AssignationItineraireCreateView, AssignationItineraireUpdateView, AssignationItineraireDeleteView,
)

app_name = 'transport_scolaire'

urlpatterns = [
      path('chauffeur',ChauffeurListView.as_view(), name='chauffeur-list'),
      path('chauffeur/<int:pk>/',ChauffeurDetailView.as_view(), name='chauffeur-detail'),
      path('chauffeur/create',ChauffeurCreateView.as_view(), name='chauffeur-create'),
      path('chauffeur/<int:pk>/update',ChauffeurUpdateView.as_view(), name='chauffeur-update'),
      path('chauffeur/<int:pk>/delete',ChauffeurDeleteView.as_view(), name='chauffeur-delete'),

      path('typevehicule',TypeVehiculeListView.as_view(), name='typevehicule-list'),
      path('typevehicule/<int:pk>/',TypeVehiculeDetailView.as_view(), name='typevehicule-detail'),
      path('typevehicule/create',TypeVehiculeCreateView.as_view(), name='typevehicule-create'),
      path('typevehicule/<int:pk>/update',TypeVehiculeUpdateView.as_view(), name='typevehicule-update'),
      path('typevehicule/<int:pk>/delete',TypeVehiculeDeleteView.as_view(), name='typevehicule-delete'),

      path('bus',BusListView.as_view(), name='bus-list'),
      path('bus/<int:pk>/',BusDetailView.as_view(), name='bus-detail'),
      path('bus/create',BusCreateView.as_view(), name='bus-create'),
      path('bus/<int:pk>/update',BusUpdateView.as_view(), name='bus-update'),
      path('bus/<int:pk>/delete',BusDeleteView.as_view(), name='bus-delete'),

      path('lieuligne',LieuLigneListView.as_view(), name='lieuligne-list'),
      path('lieuligne/<int:pk>/',LieuLigneDetailView.as_view(), name='lieuligne-detail'),
      path('lieuligne/create',LieuLigneCreateView.as_view(), name='lieuligne-create'),
      path('lieuligne/<int:pk>/update',LieuLigneUpdateView.as_view(), name='lieuligne-update'),
      path('lieuligne/<int:pk>/delete',LieuLigneDeleteView.as_view(), name='lieuligne-delete'),

      path('ligne',LigneListView.as_view(), name='ligne-list'),
      path('ligne/<int:pk>/',LigneDetailView.as_view(), name='ligne-detail'),
      path('ligne/create',LigneCreateView.as_view(), name='ligne-create'),
      path('ligne/<int:pk>/update',LigneUpdateView.as_view(), name='ligne-update'),
      path('ligne/<int:pk>/delete',LigneDeleteView.as_view(), name='ligne-delete'),

      path('lieuramassage',LieuRamassageListView.as_view(), name='lieuramassage-list'),
      path('lieuramassage/<int:pk>/',LieuRamassageDetailView.as_view(), name='lieuramassage-detail'),
      path('lieuramassage/create',LieuRamassageCreateView.as_view(), name='lieuramassage-create'),
      path('lieuramassage/<int:pk>/update',LieuRamassageUpdateView.as_view(), name='lieuramassage-update'),
      path('lieuramassage/<int:pk>/delete',LieuRamassageDeleteView.as_view(), name='lieuramassage-delete'),

      path('ordrelieu',OrdreLieuListView.as_view(), name='ordrelieu-list'),
      path('ordrelieu/<int:pk>/',OrdreLieuDetailView.as_view(), name='ordrelieu-detail'),
      path('ordrelieu/create',OrdreLieuCreateView.as_view(), name='ordrelieu-create'),
      path('ordrelieu/<int:pk>/update',OrdreLieuUpdateView.as_view(), name='ordrelieu-update'),
      path('ordrelieu/<int:pk>/delete',OrdreLieuDeleteView.as_view(), name='ordrelieu-delete'),

      path('ecole',EcoleListView.as_view(), name='ecole-list'),
      path('ecole/<int:pk>/',EcoleDetailView.as_view(), name='ecole-detail'),
      path('ecole/create',EcoleCreateView.as_view(), name='ecole-create'),
      path('ecole/<int:pk>/update',EcoleUpdateView.as_view(), name='ecole-update'),
      path('ecole/<int:pk>/delete',EcoleDeleteView.as_view(), name='ecole-delete'),

      path('classe',ClasseListView.as_view(), name='classe-list'),
      path('classe/<int:pk>/',ClasseDetailView.as_view(), name='classe-detail'),
      path('classe/create',ClasseCreateView.as_view(), name='classe-create'),
      path('classe/<int:pk>/update',ClasseUpdateView.as_view(), name='classe-update'),
      path('classe/<int:pk>/delete',ClasseDeleteView.as_view(), name='classe-delete'),

      path('parent',ParentListView.as_view(), name='parent-list'),
      path('parent/<int:pk>/',ParentDetailView.as_view(), name='parent-detail'),
      path('parent/create',ParentCreateView.as_view(), name='parent-create'),
      path('parent/<int:pk>/update',ParentUpdateView.as_view(), name='parent-update'),
      path('parent/<int:pk>/delete',ParentDeleteView.as_view(), name='parent-delete'),

      path('eleve',EleveListView.as_view(), name='eleve-list'),
      path('eleve/<int:pk>/',EleveDetailView.as_view(), name='eleve-detail'),
      path('eleve/create',EleveCreateView.as_view(), name='eleve-create'),
      path('eleve/<int:pk>/update',EleveUpdateView.as_view(), name='eleve-update'),
      path('eleve/<int:pk>/delete',EleveDeleteView.as_view(), name='eleve-delete'),

      path('itineraire',ItineraireListView.as_view(), name='itineraire-list'),
      path('itineraire/<int:pk>/',ItineraireDetailView.as_view(), name='itineraire-detail'),
      path('itineraire/create',ItineraireCreateView.as_view(), name='itineraire-create'),
      path('itineraire/<int:pk>/update',ItineraireUpdateView.as_view(), name='itineraire-update'),
      path('itineraire/<int:pk>/delete',ItineraireDeleteView.as_view(), name='itineraire-delete'),

      path('horaire',HoraireListView.as_view(), name='horaire-list'),
      path('horaire/<int:pk>/',HoraireDetailView.as_view(), name='horaire-detail'),
      path('horaire/create',HoraireCreateView.as_view(), name='horaire-create'),
      path('horaire/<int:pk>/update',HoraireUpdateView.as_view(), name='horaire-update'),
      path('horaire/<int:pk>/delete',HoraireDeleteView.as_view(), name='horaire-delete'),

      path('busassignation',BusAssignationListView.as_view(), name='busassignation-list'),
      path('busassignation/<int:pk>/',BusAssignationDetailView.as_view(), name='busassignation-detail'),
      path('busassignation/create',BusAssignationCreateView.as_view(), name='busassignation-create'),
      path('busassignation/<int:pk>/update',BusAssignationUpdateView.as_view(), name='busassignation-update'),
      path('busassignation/<int:pk>/delete',BusAssignationDeleteView.as_view(), name='busassignation-delete'),

      path('assignationitineraire',AssignationItineraireListView.as_view(), name='assignationitineraire-list'),
      path('assignationitineraire/<int:pk>/',AssignationItineraireDetailView.as_view(), name='assignationitineraire-detail'),
      path('assignationitineraire/create',AssignationItineraireCreateView.as_view(), name='assignationitineraire-create'),
      path('assignationitineraire/<int:pk>/update',AssignationItineraireUpdateView.as_view(), name='assignationitineraire-update'),
      path('assignationitineraire/<int:pk>/delete',AssignationItineraireDeleteView.as_view(), name='assignationitineraire-delete'),

]

transport_scolaire/templates/horaire/create.html
{% extends 'base.html' %}
{% block title %}
   <div class='page_title'><h3>Add Horaire</h3></div>
{% endblock title %}
{% block style %}

<style>
    .popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: white;
      padding:20px 50px;
      border-radius: 5px;
      width: 100%;
      max-width: 700px;
      border: 1px solid #ccc;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }

    .popup-buttons {
      display: flex;
      justify-content: flex-end;
      margin-top: 10px;
    }

    .popup-buttons button {
      margin-left: 10px;
    }
    .btn-search{
      position: absolute;
      right: 0px;
      top: -9px;
    }
    .pop-search{
      padding: 3px 3px;
    }
  </style>


{% endblock style %}
{% block content %}
   <form class='form-container ' method='POST' enctype='multipart/form-data'>
      {% csrf_token %}
      <div>
         <label for="pointArret">pointArret :</label>
         {{ form.pointArret }}
         {% for error in form.pointArret.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="itineraire">itineraire :</label>
         {{ form.itineraire }}
         {% for error in form.itineraire.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="heureDebut">heureDebut :</label>
         {{ form.heureDebut }}
         {% for error in form.heureDebut.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="heureFin">heureFin :</label>
         {{ form.heureFin }}
         {% for error in form.heureFin.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <button type='submit' class='btn btn-primary text-white' >save</button>
   </form>
{% endblock content %}
{% block script %}

<script>
    const app = Vue.createApp({
      data() {
        return {

                }
            },
      methods: {

      },
    
      mounted() {

      }
    })

    app.mount('#app')
  </script>
   <script>
   console.log("Hello World Generator")
   
   </script>
{% endblock script %}

transport_scolaire/templates/horaire/delete.html
{% extends 'base.html' %}
{% block title %}
   <div class='page_title'><h3>Delete Horaire</h3></div>
{% endblock title %}
{% block content %}
   <form class='form-container' id='delete-object-form' method='POST'>
      {% csrf_token %}
      <button type='button' class='btn btn-danger text-white' data-bs-toggle='modal' data-bs-target='#confirmDeleteModal'><i class='fas fa-trash'></i> Delete</button>
   </form>
{% endblock content %}
{% block script %}
      <script>
         $(document).ready(function() {
            $('button[name="delete_button"]').click(function(event) {
               event.preventDefault();
               $('#confirmDeleteModal').modal('show');
            });
            $('.modal-confirm').click(function(event) {
               event.preventDefault();
               $('form#delete-object-form').submit();
            });
         });
   </script>
{% endblock script %}
{% block modal %}
   <div class='modal fade' id='confirmDeleteModal' tabindex='-1' role='dialog' aria-labelledby='confirmDeleteModalLabel' aria-hidden='true'>
      <div class='modal-dialog' role='document'>
         <div class='modal-content'>
            <div class='modal-header'>
               <h5 class='modal-title' id='confirmDeleteModalLabel'>Confirm Delete</h5>
               <button type='button' class='close' data-bs-dismiss='modal' aria-label='Close'>
                  <span aria-hidden='true'>&times;</span>
               </button>
            </div>
            <div class='modal-body'>
               <p>Are you sure you want to delete this Horaire?</p>
            </div>
            <div class='modal-footer'>
               <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancel</button>
               <button type='submit' id='btn-final-confirm' class='btn btn-danger modal-confirm'>Delete</button>
            </div>
         </div>
      </div>
   </div>
{% endblock modal %}

transport_scolaire/templates/horaire/detail.html
{% extends 'base.html' %}
{% block title %}
   <div class='page_title'><h3>Horaire</h3></div>
{% endblock title %}
{% block content %}
   <div class='actions'>
      <a href='{% url 'transport_scolaire:horaire-list' %}'  class='btn btn-outline-primary text-primary'>
         <i class="fa-solid fa-list-ul"></i> <span style="margin-left:10px;">List</span>   </a>
                  <a class='update btn btn-outline-secondary text-secondary' href="{% url 'transport_scolaire:horaire-update' object.pk %}"><i class='fa-solid fa-pen-to-square'></i><span style="margin-left:10px;">Edit</span></a>
                  <a class='delete btn btn-outline-danger text-danger' href="{% url 'transport_scolaire:horaire-delete' object.pk %}"><i class='fa-solid fa-trash-can'></i><span style="margin-left:10px;">Delete</span></a>
   </div>
   <div class='table-responsive'>
      <table class='table'>
         <tbody>
            <tr>
               <td>pointArret</td><td>{{object.pointArret}}</td>
            </tr>
            <tr>
               <td>itineraire</td><td>{{object.itineraire}}</td>
            </tr>
            <tr>
               <td>heureDebut</td><td>{{object.heureDebut}}</td>
            </tr>
            <tr>
               <td>heureFin</td><td>{{object.heureFin}}</td>
            </tr>
         </tbody>
      </table>
   </div>
{% endblock content %}

transport_scolaire/templates/horaire/list.html
{% extends 'base.html' %}
{% block title %}
   <div class='page_title'><h3>Horaire List</h3></div>
{% endblock title %}
{% block content %}
   <div class='actions'>
      <a href='{% url 'transport_scolaire:horaire-create' %}' class='btn btn-primary text-white'>
         Add New horaire
   </a>
   </div>
   <form class='form-search'  method='GET'>
   <div class='content-search'>
         <div class='d-flex group flex-column '>            <label>pointArret</label>            <select type='text'  name='search_filter_pointArret'>
<option value=''>-----------</option>{% for pointArret in pointArrets %}
<option {% if search_filter_pointArret|stringformat:"s" == pointArret.pk|stringformat:"s" %}selected{% endif %}  value='{{pointArret.pk}}'>{{pointArret}}</option>{% endfor %}
         <select type='text' name='search_filter'>
         </div>         <div class='d-flex group flex-column '>            <label>itineraire</label>            <select type='text'  name='search_filter_itineraire'>
<option value=''>-----------</option>{% for itineraire in itineraires %}
<option {% if search_filter_itineraire|stringformat:"s" == itineraire.pk|stringformat:"s" %}selected{% endif %}  value='{{itineraire.pk}}'>{{itineraire}}</option>{% endfor %}
         <select type='text' name='search_filter'>
         </div>         <button type='submit' class='btn btn-primary sub-2 text-white' >Search</button>
   </div>
   </form>
   <form class='form-search'  method='GET'>
         <input type='text' name='search_query' value='{{search_query}}' placeholder='search...'>
         <button type='submit' class='btn btn-primary text-white' >Search</button>
   </form>
   <div class='table-responsive'>
      <table class='table'>
         <thead>
            <tr>
               <th>N°</th>
               <th>pointArret</th>
               <th>itineraire</th>
               <th>heureDebut</th>
               <th>heureFin</th>
               <th>Actions<th>
            </tr>
         </thead>
         <tbody>
         {% for horaire in horaires %}
            <tr>
               <td>{{ horaire.pk }}</td>
               <td>{{ horaire.pointArret }}</td>
               <td>{{ horaire.itineraire }}</td>
               <td>{{ horaire.heureDebut }}</td>
               <td>{{ horaire.heureFin }}</td>
               <td class='col-actions'>
                  <a class='see btn btn-outline-primary text-primary' href="{% url 'transport_scolaire:horaire-detail' horaire.pk %}"><i class='fa-solid fa-eye'></i></a>
                  <a class='update btn btn-outline-secondary text-secondary' href="{% url 'transport_scolaire:horaire-update' horaire.pk %}"><i class='fa-solid fa-pen-to-square'></i></a>
                  <a class='delete btn btn-outline-danger text-danger' href="{% url 'transport_scolaire:horaire-delete' horaire.pk %}"><i class='fa-solid fa-trash-can'></i></a>
               </td>
            </tr>
         {% endfor %}
         </tbody>
      </table>
   </div>

<div class="panigation">
            <span>
               <span>
                   Page {{ horaires.number }} sur {{ horaires.paginator.num_pages }}.

               </span>
               {% if horaires.has_previous %}
                   <a href="?page=1">premiere</a>
                   <a href="?page={{ horaires.previous_page_number }}">precedente</a>
               {% endif %}


               {% if horaires.has_next %}
                   <a href="?page={{ horaires.next_page_number }}">suivante</a>

                   <a href="?page={{ horaires.paginator.num_pages }}">derniere</a>
               {% endif %}
           </span>
       </div>
  
{% endblock content %}

transport_scolaire/templates/horaire/update.html
{% extends 'base.html' %}
{% block title %}
   <div class='page_title'><h3>Edit Horaire</h3></div>
{% endblock title %}
{% block style %}

<style>
    .popup {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: white;
      padding:20px 50px;
      border-radius: 5px;
      width: 100%;
      max-width: 700px;
      border: 1px solid #ccc;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }

    .popup-buttons {
      display: flex;
      justify-content: flex-end;
      margin-top: 10px;
    }

    .popup-buttons button {
      margin-left: 10px;
    }
    .btn-search{
      position: absolute;
      right: 0px;
      top: -9px;
    }
    .pop-search{
      padding: 3px 3px;
    }
  </style>


{% endblock style %}
{% block content %}
   <form class='form-container ' method='POST' enctype='multipart/form-data'>
      <div class='actions'>
      <a href='{% url 'transport_scolaire:horaire-list' %}'  class='btn btn-outline-primary text-primary'>
         <i class="fa-solid fa-list-ul"></i> <span style="margin-left:10px;">List</span>   </a>
                  <a class='delete btn btn-outline-danger text-danger' href="{% url 'transport_scolaire:horaire-delete' object.pk %}"><i class='fa-solid fa-trash-can'></i><span style="margin-left:10px;">Delete</span></a>
      {% csrf_token %}
      </div>
      <div>
         <label for="pointArret">pointArret :</label>
         {{ form.pointArret }}
         {% for error in form.pointArret.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="itineraire">itineraire :</label>
         {{ form.itineraire }}
         {% for error in form.itineraire.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="heureDebut">heureDebut :</label>
         {{ form.heureDebut }}
         {% for error in form.heureDebut.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <div>
         <label for="heureFin">heureFin :</label>
         {{ form.heureFin }}
         {% for error in form.heureFin.errors %}
         <div class="text-danger">{{ error }}</div>
         {% endfor %}
      </div>
      <button type='submit' class='btn btn-primary text-white' >update</button>
   </form>
{% endblock content %}
{% block script %}

<script>
    const app = Vue.createApp({
      data() {
        return {

                }
            },
      methods: {

      },
    
      mounted() {

      }
    })

    app.mount('#app')
  </script>
   <script>
   console.log("Hello World Generator")
   
   </script>
{% endblock script %}